org.gradle.jvmargs=-Xmx5120M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx5120M -XX:MaxMetaspaceSize=1024m
kotlin.code.style=official
org.gradle.caching=false
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
org.gradle.configuration-cache=false
kotlin.js.nodejs.download=true
kotlin.wasm.es.modules=true
kotlin.js.generate.executable.default=true
