org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m
kotlin.code.style=official
org.gradle.caching=false
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
org.gradle.configuration-cache=false
kotlin.js.nodejs.download=true
kotlin.js.yarn.enabled=false
kotlin.wasm.es.modules=true
kotlin.js.generate.executable.default=true
org.jetbrains.compose.experimental.jscanvas.enabled=true
