org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
kotlin.daemon.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m
kotlin.code.style=official
org.gradle.caching=false
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
org.gradle.configuration-cache=false
kotlin.js.node.version=25.0.0
kotlin.js.node.download.base.url=file:///C:/Users/AUTENTIIC/AppData/Local/Temp/opencode/nodemirror
kotlin.js.nodejs.download=true
kotlin.wasmJs.node.version=25.0.0
kotlin.wasmJs.node.download.base.url=file:///C:/Users/AUTENTIIC/AppData/Local/Temp/opencode/nodemirror
org.jetbrains.compose.experimental.jscanvas.enabled=true
android.builtInKotlin=false
android.newDsl=false
