package com.tik_market.navigation

sealed class NavScreen(val route: String, val title: String) {
    object Home : NavScreen("home", "Accueil")
    object Cart : NavScreen("cart", "Panier")
    object Profile : NavScreen("profile", "Mon Compte")
    object ProductDetail : NavScreen("product", "Détail")
    object Chat : NavScreen("chat", "Chat")
    object Conversations : NavScreen("conversations", "Messages")
    object Orders : NavScreen("orders", "Commandes")
    object Settings : NavScreen("settings", "Paramètres")
    // Nouveaux écrans
    object Auth : NavScreen("auth", "Connexion")
    object VendorDashboard : NavScreen("vendor", "Tableau de bord")
    object AddProduct : NavScreen("add-product", "Ajouter produit")
    object Checkout : NavScreen("checkout", "Commander")
    object Payment : NavScreen("payment", "Paiement")
    object CreateShop : NavScreen("create-shop", "Créer ma boutique")
    object VendorOrders : NavScreen("vendor-orders", "Commandes reçues")
    object ManageShop : NavScreen("manage-shop", "Gérer ma boutique")
    object ShopsList : NavScreen("shops-list", "Liste des boutiques")
    object Wishlist : NavScreen("wishlist", "Favoris")
    object AdminDashboard : NavScreen("admin", "Admin")
    object Notifications : NavScreen("notifications", "Notifications")
    object ShopPage : NavScreen("shop-page", "Boutique")
    object Compare : NavScreen("compare", "Comparer")
    object BarcodeScan : NavScreen("barcode", "Scan code-barres")
    object StoryViewer : NavScreen("story-viewer", "Story")
    object VendorGroupBuys : NavScreen("vendor-group-buys", "Achats groupés")
    object VendorSubscribers : NavScreen("vendor-subscribers", "Abonnés")
    object FollowedShops : NavScreen("followed-shops", "Boutiques suivies")
    object Loyalty : NavScreen("loyalty", "Programme fidélité")
    object NotifPrefs : NavScreen("notif-prefs", "Préférences notifications")
    object MyGroupBuys : NavScreen("my-group-buys", "Mes achats groupés")
    object ShopsMap : NavScreen("shops-map", "Carte des boutiques")
    object EditProfile : NavScreen("edit-profile", "Modifier le profil")
    object Splash : NavScreen("splash", "TiK-Market")
}
