package com.tik_market.utils

data class AppStrings(
    val appName: String,
    val home: String,
    val search: String,
    val cart: String,
    val profile: String,
    val messages: String,
    val notifications: String,
    val settings: String,
    val orders: String,
    val wishlist: String,
    val productDetail: String,
    val addToCart: String,
    val buyNow: String,
    val chat: String,
    val share: String,
    val report: String,
    val reportProduct: String,
    val category: String,
    val allCategories: String,
    val priceRange: String,
    val min: String,
    val max: String,
    val clear: String,
    val noProducts: String,
    val noReviews: String,
    val giveReview: String,
    val publishReview: String,
    val yourComment: String,
    val submit: String,
    val cancel: String,
    val confirm: String,
    val loading: String,
    val error: String,
    val retry: String,
    val logout: String,
    val login: String,
    val register: String,
    val vendor: String,
    val verifiedVendor: String,
    val whatsapp: String,
    val call: String,
    val payment: String,
    val payNow: String,
    val chooseOperator: String,
    val phoneNumber: String,
    val recap: String,
    val back: String,
    val reviews: String,
    val language: String,
    val french: String,
    val english: String,
    val darkMode: String,
    val unknown: String,
    val myPosition: String,
    val openInMaps: String,
    val send: String,
    val voice: String,
    val file: String,
    val image: String,
    val photo: String,
    val location: String,
    val emoji: String,
    val typeMessage: String,
    val searchProducts: String,
    val noConversations: String,
    val orderStatusPending: String,
    val orderStatusPaid: String,
    val orderStatusProcessing: String,
    val orderStatusShipped: String,
    val orderStatusDelivered: String,
    val orderStatusCancelled: String,
    val total: String,
    val items: String,
    val shippingAddress: String,
    val notes: String,
    val createOrder: String,
    val checkout: String,
    val shop: String,
    val seller: String,
    val loadingMore: String,
    val pullToRefresh: String,
)

val FR = AppStrings(
    appName = "TiK-Market",
    home = "Accueil",
    search = "Rechercher",
    cart = "Panier",
    profile = "Mon Compte",
    messages = "Messages",
    notifications = "Notifications",
    settings = "Paramètres",
    orders = "Commandes",
    wishlist = "Favoris",
    productDetail = "Détails du produit",
    addToCart = "Ajouter au panier",
    buyNow = "Commander",
    chat = "Discuter",
    share = "Partager",
    report = "Signaler",
    reportProduct = "Signaler ce produit",
    category = "Catégorie",
    allCategories = "Tout",
    priceRange = "Prix",
    min = "Min",
    max = "Max",
    clear = "Effacer",
    noProducts = "Aucun produit trouvé",
    noReviews = "Aucun avis pour le moment",
    giveReview = "Donner mon avis",
    publishReview = "Publier mon avis",
    yourComment = "Votre commentaire (optionnel)...",
    submit = "Envoyer",
    cancel = "Annuler",
    confirm = "Confirmer",
    loading = "Chargement...",
    error = "Erreur",
    retry = "Réessayer",
    logout = "Déconnexion",
    login = "Connexion",
    register = "Inscription",
    vendor = "Vendeur",
    verifiedVendor = "Vendeur vérifié",
    whatsapp = "WhatsApp",
    call = "Appeler",
    payment = "Paiement",
    payNow = "Payer",
    chooseOperator = "Choisissez votre opérateur",
    phoneNumber = "Numéro Mobile Money",
    recap = "Récapitulatif",
    back = "Retour",
    reviews = "Avis & Notes",
    language = "Langue",
    french = "Français",
    english = "English",
    darkMode = "Mode sombre",
    unknown = "Inconnu",
    myPosition = "Ma position",
    openInMaps = "Ouvrir dans Maps",
    send = "Envoyer",
    voice = "Vocal",
    file = "Fichier",
    image = "Image",
    photo = "Photo",
    location = "Localisation",
    emoji = "Émoji",
    typeMessage = "Écrivez un message...",
    searchProducts = "Rechercher un produit...",
    noConversations = "Aucune conversation",
    orderStatusPending = "En attente de paiement",
    orderStatusPaid = "Payée",
    orderStatusProcessing = "En cours",
    orderStatusShipped = "Expédiée",
    orderStatusDelivered = "Livrée",
    orderStatusCancelled = "Annulée",
    total = "Total",
    items = "article(s)",
    shippingAddress = "Adresse de livraison",
    notes = "Notes",
    createOrder = "Commander",
    checkout = "Finaliser la commande",
    shop = "Boutique",
    seller = "Vendeur",
    loadingMore = "Chargement...",
    pullToRefresh = "Tirez pour actualiser",
)

val EN = AppStrings(
    appName = "TiK-Market",
    home = "Home",
    search = "Search",
    cart = "Cart",
    profile = "My Account",
    messages = "Messages",
    notifications = "Notifications",
    settings = "Settings",
    orders = "Orders",
    wishlist = "Wishlist",
    productDetail = "Product Details",
    addToCart = "Add to Cart",
    buyNow = "Buy Now",
    chat = "Chat",
    share = "Share",
    report = "Report",
    reportProduct = "Report this product",
    category = "Category",
    allCategories = "All",
    priceRange = "Price",
    min = "Min",
    max = "Max",
    clear = "Clear",
    noProducts = "No products found",
    noReviews = "No reviews yet",
    giveReview = "Give a review",
    publishReview = "Publish review",
    yourComment = "Your comment (optional)...",
    submit = "Submit",
    cancel = "Cancel",
    confirm = "Confirm",
    loading = "Loading...",
    error = "Error",
    retry = "Retry",
    logout = "Logout",
    login = "Login",
    register = "Sign Up",
    vendor = "Seller",
    verifiedVendor = "Verified seller",
    whatsapp = "WhatsApp",
    call = "Call",
    payment = "Payment",
    payNow = "Pay Now",
    chooseOperator = "Choose your operator",
    phoneNumber = "Mobile Money Number",
    recap = "Summary",
    back = "Back",
    reviews = "Reviews & Ratings",
    language = "Language",
    french = "Français",
    english = "English",
    darkMode = "Dark mode",
    unknown = "Unknown",
    myPosition = "My location",
    openInMaps = "Open in Maps",
    send = "Send",
    voice = "Voice",
    file = "File",
    image = "Image",
    photo = "Photo",
    location = "Location",
    emoji = "Emoji",
    typeMessage = "Type a message...",
    searchProducts = "Search products...",
    noConversations = "No conversations",
    orderStatusPending = "Awaiting payment",
    orderStatusPaid = "Paid",
    orderStatusProcessing = "Processing",
    orderStatusShipped = "Shipped",
    orderStatusDelivered = "Delivered",
    orderStatusCancelled = "Cancelled",
    total = "Total",
    items = "item(s)",
    shippingAddress = "Shipping address",
    notes = "Notes",
    createOrder = "Place order",
    checkout = "Checkout",
    shop = "Shop",
    seller = "Seller",
    loadingMore = "Loading...",
    pullToRefresh = "Pull to refresh",
)

fun getStrings(lang: String): AppStrings = if (lang == "en") EN else FR
