package com.tik_market.utils

import androidx.compose.runtime.staticCompositionLocalOf

/** CompositionLocal exposing the app-wide strings for the current language. */
val LocalAppStrings = staticCompositionLocalOf<AppStrings> { FR }

data class AppStrings(
    val appName: String,
    val home: String,
    val search: String,
    val cart: String,
    val profile: String,
    val messages: String,
    val notifications: String,
    val settings: String,
    val orders: String,
    val wishlist: String,
    val productDetail: String,
    val addToCart: String,
    val buyNow: String,
    val chat: String,
    val share: String,
    val report: String,
    val reportProduct: String,
    val category: String,
    val allCategories: String,
    val priceRange: String,
    val min: String,
    val max: String,
    val clear: String,
    val noProducts: String,
    val noReviews: String,
    val giveReview: String,
    val publishReview: String,
    val yourComment: String,
    val submit: String,
    val cancel: String,
    val confirm: String,
    val loading: String,
    val error: String,
    val retry: String,
    val logout: String,
    val login: String,
    val register: String,
    val vendor: String,
    val verifiedVendor: String,
    val whatsapp: String,
    val call: String,
    val payment: String,
    val payNow: String,
    val chooseOperator: String,
    val phoneNumber: String,
    val recap: String,
    val back: String,
    val reviews: String,
    val language: String,
    val french: String,
    val english: String,
    val darkMode: String,
    val unknown: String,
    val myPosition: String,
    val openInMaps: String,
    val send: String,
    val voice: String,
    val file: String,
    val image: String,
    val photo: String,
    val location: String,
    val emoji: String,
    val typeMessage: String,
    val searchProducts: String,
    val noConversations: String,
    val orderStatusPending: String,
    val orderStatusPaid: String,
    val orderStatusProcessing: String,
    val orderStatusShipped: String,
    val orderStatusDelivered: String,
    val orderStatusCancelled: String,
    val total: String,
    val items: String,
    val shippingAddress: String,
    val notes: String,
    val createOrder: String,
    val checkout: String,
    val shop: String,
    val seller: String,
    val loadingMore: String,
    val pullToRefresh: String,
    val account: String,
    val pressBackToExit: String,
    val offlineBanner: String,
    val connectionRestored: String,
    val connectionLost: String,
    val sessionExpired: String,
    // Auth
    val signIn: String,
    val signUp: String,
    val authOtpTitle: String,
    val phoneLogin: String,
    val loginContinue: String,
    val createYourAccount: String,
    val continueWithGoogle: String,
    val useEmailPassword: String,
    val or: String,
    val noAccountSignup: String,
    val alreadyAccountLogin: String,
    val createAccountTitle: String,
    val fullName: String,
    val phone: String,
    val email: String,
    val passwordLabel: String,
    val confirmPasswordLabel: String,
    val acceptTerms: String,
    val andPrivacy: String,
    val loginBtn: String,
    val signupBtn: String,
    val chooseYourCity: String,
    val cityLabel: String,
    val selectYourCity: String,
    val receiveCodeSms: String,
    val sentTo: String,
    val sixDigitCode: String,
    val codeValidFor: String,
    val verify: String,
    val resendCode: String,
    val changeNumber: String,
    val other: String,
    val sendCode: String,
    val chooseCityRequired: String,
    val nameRequired: String,
    val phoneRequired: String,
    val invalidPhone: String,
    val emailRequired: String,
    val invalidEmail: String,
    val passwordRequired: String,
    val passwordTooShort: String,
    val confirmRequired: String,
    val passwordsDontMatch: String,
    val acceptTermsRequired: String,
    val invalidNumberExample: String,
    val codeTooShort: String,
    val incorrectCode: String,
    val serverLoginFailed: String,
    val googleLoginFailed: String,
    val sendingError: String,
    val authErrorPrefix: String,
)

val FR = AppStrings(
    appName = "TiK-Market",
    home = "Accueil",
    search = "Rechercher",
    cart = "Panier",
    profile = "Mon Compte",
    messages = "Messages",
    notifications = "Notifications",
    settings = "Paramètres",
    orders = "Commandes",
    wishlist = "Favoris",
    productDetail = "Détails du produit",
    addToCart = "Ajouter au panier",
    buyNow = "Commander",
    chat = "Discuter",
    share = "Partager",
    report = "Signaler",
    reportProduct = "Signaler ce produit",
    category = "Catégorie",
    allCategories = "Tout",
    priceRange = "Prix",
    min = "Min",
    max = "Max",
    clear = "Effacer",
    noProducts = "Aucun produit trouvé",
    noReviews = "Aucun avis pour le moment",
    giveReview = "Donner mon avis",
    publishReview = "Publier mon avis",
    yourComment = "Votre commentaire (optionnel)...",
    submit = "Envoyer",
    cancel = "Annuler",
    confirm = "Confirmer",
    loading = "Chargement...",
    error = "Erreur",
    retry = "Réessayer",
    logout = "Déconnexion",
    login = "Connexion",
    register = "Inscription",
    vendor = "Vendeur",
    verifiedVendor = "Vendeur vérifié",
    whatsapp = "WhatsApp",
    call = "Appeler",
    payment = "Paiement",
    payNow = "Payer",
    chooseOperator = "Choisissez votre opérateur",
    phoneNumber = "Numéro Mobile Money",
    recap = "Récapitulatif",
    back = "Retour",
    reviews = "Avis & Notes",
    language = "Langue",
    french = "Français",
    english = "English",
    darkMode = "Mode sombre",
    unknown = "Inconnu",
    myPosition = "Ma position",
    openInMaps = "Ouvrir dans Maps",
    send = "Envoyer",
    voice = "Vocal",
    file = "Fichier",
    image = "Image",
    photo = "Photo",
    location = "Localisation",
    emoji = "Émoji",
    typeMessage = "Écrivez un message...",
    searchProducts = "Rechercher un produit...",
    noConversations = "Aucune conversation",
    orderStatusPending = "En attente de paiement",
    orderStatusPaid = "Payée",
    orderStatusProcessing = "En cours",
    orderStatusShipped = "Expédiée",
    orderStatusDelivered = "Livrée",
    orderStatusCancelled = "Annulée",
    total = "Total",
    items = "article(s)",
    shippingAddress = "Adresse de livraison",
    notes = "Notes",
    createOrder = "Commander",
    checkout = "Finaliser la commande",
    shop = "Boutique",
    seller = "Vendeur",
    loadingMore = "Chargement...",
    pullToRefresh = "Tirez pour actualiser",
    account = "Compte",
    pressBackToExit = "Appuyez encore pour quitter",
    offlineBanner = "🔴 Connexion perdue — certaines fonctionnalités peuvent être limitées",
    connectionRestored = "✅ Connexion rétablie",
    connectionLost = "🔴 Connexion perdue",
    sessionExpired = "Session expirée",
    signIn = "S'identifier",
    signUp = "Inscription",
    authOtpTitle = "Vérification OTP",
    phoneLogin = "Connexion Téléphone",
    loginContinue = "Connectez-vous pour continuer",
    createYourAccount = "Créez votre compte",
    continueWithGoogle = "Continuer avec Google",
    useEmailPassword = "Utiliser Email / Mot de passe",
    or = "ou",
    noAccountSignup = "Pas encore de compte ? S'inscrire",
    alreadyAccountLogin = "Déjà inscrit ? Se connecter",
    createAccountTitle = "Créer un compte",
    fullName = "Nom complet",
    phone = "Téléphone",
    email = "Email",
    passwordLabel = "Mot de passe",
    confirmPasswordLabel = "Confirmer le mot de passe",
    acceptTerms = "J'accepte les Conditions d'Utilisation",
    andPrivacy = "et la Politique de Confidentialité",
    loginBtn = "Se connecter",
    signupBtn = "S'inscrire",
    chooseYourCity = "Choisir votre ville",
    cityLabel = "Ville",
    selectYourCity = "Sélectionnez votre ville",
    receiveCodeSms = "Recevez un code par SMS",
    sentTo = "Envoyé au +237 %s",
    sixDigitCode = "Code à 6 chiffres",
    codeValidFor = "Code valable %ds",
    verify = "Vérifier",
    resendCode = "Renvoyer le code",
    changeNumber = "Changer de numéro",
    other = "Autre",
    sendCode = "Envoyer le code",
    chooseCityRequired = "Veuillez choisir votre ville avant de continuer",
    nameRequired = "Nom requis",
    phoneRequired = "Téléphone requis",
    invalidPhone = "Numéro invalide (8+ chiffres)",
    emailRequired = "Email requis",
    invalidEmail = "Email invalide",
    passwordRequired = "Mot de passe requis",
    passwordTooShort = "4 caractères minimum",
    confirmRequired = "Confirmation requise",
    passwordsDontMatch = "Les mots de passe ne correspondent pas",
    acceptTermsRequired = "Veuillez accepter les conditions d'utilisation",
    invalidNumberExample = "Numéro invalide (ex: 691234567)",
    codeTooShort = "Code trop court",
    incorrectCode = "Code incorrect",
    serverLoginFailed = "Échec de la connexion au serveur",
    googleLoginFailed = "Échec ou annulation de la connexion Google",
    sendingError = "Erreur d'envoi",
    authErrorPrefix = "Erreur",
)

val EN = AppStrings(
    appName = "TiK-Market",
    home = "Home",
    search = "Search",
    cart = "Cart",
    profile = "My Account",
    messages = "Messages",
    notifications = "Notifications",
    settings = "Settings",
    orders = "Orders",
    wishlist = "Wishlist",
    productDetail = "Product Details",
    addToCart = "Add to Cart",
    buyNow = "Buy Now",
    chat = "Chat",
    share = "Share",
    report = "Report",
    reportProduct = "Report this product",
    category = "Category",
    allCategories = "All",
    priceRange = "Price",
    min = "Min",
    max = "Max",
    clear = "Clear",
    noProducts = "No products found",
    noReviews = "No reviews yet",
    giveReview = "Give a review",
    publishReview = "Publish review",
    yourComment = "Your comment (optional)...",
    submit = "Submit",
    cancel = "Cancel",
    confirm = "Confirm",
    loading = "Loading...",
    error = "Error",
    retry = "Retry",
    logout = "Logout",
    login = "Login",
    register = "Sign Up",
    vendor = "Seller",
    verifiedVendor = "Verified seller",
    whatsapp = "WhatsApp",
    call = "Call",
    payment = "Payment",
    payNow = "Pay Now",
    chooseOperator = "Choose your operator",
    phoneNumber = "Mobile Money Number",
    recap = "Summary",
    back = "Back",
    reviews = "Reviews & Ratings",
    language = "Language",
    french = "Français",
    english = "English",
    darkMode = "Dark mode",
    unknown = "Unknown",
    myPosition = "My location",
    openInMaps = "Open in Maps",
    send = "Send",
    voice = "Voice",
    file = "File",
    image = "Image",
    photo = "Photo",
    location = "Location",
    emoji = "Emoji",
    typeMessage = "Type a message...",
    searchProducts = "Search products...",
    noConversations = "No conversations",
    orderStatusPending = "Awaiting payment",
    orderStatusPaid = "Paid",
    orderStatusProcessing = "Processing",
    orderStatusShipped = "Shipped",
    orderStatusDelivered = "Delivered",
    orderStatusCancelled = "Cancelled",
    total = "Total",
    items = "item(s)",
    shippingAddress = "Shipping address",
    notes = "Notes",
    createOrder = "Place order",
    checkout = "Checkout",
    shop = "Shop",
    seller = "Seller",
    loadingMore = "Loading...",
    pullToRefresh = "Pull to refresh",
    account = "Account",
    pressBackToExit = "Press back again to exit",
    offlineBanner = "🔴 Connection lost — some features may be limited",
    connectionRestored = "✅ Connection restored",
    connectionLost = "🔴 Connection lost",
    sessionExpired = "Session expired",
    signIn = "Sign in",
    signUp = "Sign up",
    authOtpTitle = "OTP Verification",
    phoneLogin = "Phone Login",
    loginContinue = "Log in to continue",
    createYourAccount = "Create your account",
    continueWithGoogle = "Continue with Google",
    useEmailPassword = "Use Email / Password",
    or = "or",
    noAccountSignup = "No account yet? Sign up",
    alreadyAccountLogin = "Already registered? Log in",
    createAccountTitle = "Create an account",
    fullName = "Full name",
    phone = "Phone",
    email = "Email",
    passwordLabel = "Password",
    confirmPasswordLabel = "Confirm password",
    acceptTerms = "I accept the Terms of Use",
    andPrivacy = "and the Privacy Policy",
    loginBtn = "Log in",
    signupBtn = "Sign up",
    chooseYourCity = "Choose your city",
    cityLabel = "City",
    selectYourCity = "Select your city",
    receiveCodeSms = "You will receive an SMS code",
    sentTo = "Sent to +237 %s",
    sixDigitCode = "6-digit code",
    codeValidFor = "Code valid for %ds",
    verify = "Verify",
    resendCode = "Resend code",
    changeNumber = "Change number",
    other = "Other",
    sendCode = "Send code",
    chooseCityRequired = "Please choose your city before continuing",
    nameRequired = "Name is required",
    phoneRequired = "Phone is required",
    invalidPhone = "Invalid number (8+ digits)",
    emailRequired = "Email is required",
    invalidEmail = "Invalid email",
    passwordRequired = "Password is required",
    passwordTooShort = "Minimum 4 characters",
    confirmRequired = "Confirmation is required",
    passwordsDontMatch = "Passwords do not match",
    acceptTermsRequired = "Please accept the Terms of Use",
    invalidNumberExample = "Invalid number (e.g. 691234567)",
    codeTooShort = "Code too short",
    incorrectCode = "Incorrect code",
    serverLoginFailed = "Server login failed",
    googleLoginFailed = "Google login failed or cancelled",
    sendingError = "Error sending",
    authErrorPrefix = "Error",
)

fun getStrings(lang: String): AppStrings = if (lang == "en") EN else FR
